// admin/src/components/Amis/src/AMISRenderer.tsx
import * as React from 'react';
import axios from 'axios';
// import copy from 'copy-to-clipboard';

import {render as renderAmis, ToastComponent, AlertComponent} from 'amis';
import {alert, confirm} from 'amis/lib/components/Alert';
import {toast} from 'amis/lib/components/Toast';

export class AMISReactRenderer extends React.Component<any, any> {
  render() {
    let amisScoped;
    let theme = 'cxd';
    let locale = 'zh-CN';

    // 请勿使用 React.StrictMode，目前还不支持
    return (
      <div>
        <p>通过 amis 渲染页面</p>
        <ToastComponent
          theme={theme}
          key="toast"
          position={'top-right'}
          locale={locale}
        />
        <AlertComponent theme={theme} key="alert" locale={locale} />
        {renderAmis(
          {
            // 这里是 amis 的 Json 配置。
            type: 'page',
            title: '简单页面',
            body: '内容'
          },
          {
            // props...
            locale: 'en-US', // 请参考「多语言」的文档
            scopeRef: (ref: any) => (amisScoped = ref)  // 功能和前面 SDK 的 amisScoped 一样
          },
          {
            // 下面三个接口必须实现
            fetcher: ({
              url, // 接口地址
              method, // 请求方法 get、post、put、delete
              data, // 请求数据
              responseType,
              config, // 其他配置
              headers // 请求头
            }: any) => {
              config = config || {};
              config.withCredentials = true;
              responseType && (config.responseType = responseType);

              if (config.cancelExecutor) {
                config.cancelToken = new (axios as any).CancelToken(
                  config.cancelExecutor
                );
              }

              config.headers = headers || {};

              if (method !== 'post' && method !== 'put' && method !== 'patch') {
                if (data) {
                  config.params = data;
                }

                return (axios as any)[method](url, config);
              } else if (data && data instanceof FormData) {
                config.headers = config.headers || {};
                config.headers['Content-Type'] = 'multipart/form-data';
              } else if (
                data &&
                typeof data !== 'string' &&
                !(data instanceof Blob) &&
                !(data instanceof ArrayBuffer)
              ) {
                data = JSON.stringify(data);
                config.headers = config.headers || {};
                config.headers['Content-Type'] = 'application/json';
              }

              return (axios as any)[method](url, data, config);
            },
            isCancel: (value: any) => (axios as any).isCancel(value),
            copy: content => {
              // copy(content);
              toast.success('内容已复制到粘贴板');
            },
            theme

            // 后面这些接口可以不用实现

            // 默认是地址跳转
            // jumpTo: (
            //   location: string /*目标地址*/,
            //   action: any /* action对象*/
            // ) => {
            //   // 用来实现页面跳转, actionType:link、url 都会进来。
            // },

            // updateLocation: (
            //   location: string /*目标地址*/,
            //   replace: boolean /*是replace，还是push？*/
            // ) => {
            //   // 地址替换，跟 jumpTo 类似
            // },

            // isCurrentUrl: (
            //   url: string /*url地址*/,
            // ) => {
            //   // 用来判断是否目标地址当前地址
            // },

            // notify: (
            //   type: 'error' | 'success' /**/,
            //   msg: string /*提示内容*/
            // ) => {
            //   toast[type]
            //     ? toast[type](msg, type === 'error' ? '系统错误' : '系统消息')
            //     : console.warn('[Notify]', type, msg);
            // },
            // alert,
            // confirm,
            // tracker: (eventTracke) => {}
          }
        )}
      </div>
    );
  }
}

// admin/src/components/Amis/src/AMISRenderer.vue
<template>
  <div className="amis-renderer-box">
    <div ref="rendererBox"></div>
  </div>
</template>

<script>
import { render as renderSchema } from 'amis'
// import copy from 'copy-to-clipboard'
// import './style/themes/antd.less'
import './style/themes/cxd.less'
import ReactDOM from 'react-dom'
import * as qs from 'qs'
import { toast, alert, confirm } from 'amis'
import axios from 'axios'

export default {
  props: {
    schema: {
      type: Object,
    },
    updateLocation: {
      type: Function,
    },
    onAction: {
      type: Function,
    },
  },
  data() {
    return {
      theme: 'default',
    }
  },

  mounted() {
    this.initEnv()
    ReactDOM.render(
      renderSchema(
        this.schema,
        {
          onAction: this.onAction || this.handleAction,
          theme: this.theme,
        },
        this.env,
      ),
      this.$refs.rendererBox,
    )
  },

  methods: {
    initEnv() {
      this.env = {
        session: 'global',
        updateLocation: this.updateLocation || this.updateRoute,
        isCurrentUrl: (to) => {
          const link = this.normalizeLink(to)
          const location = window.location
          let pathname = link
          let search = ''
          const idx = link.indexOf('?')
          if (~idx) {
            pathname = link.substring(0, idx)
            search = link.substring(idx)
          }
          if (search) {
            if (pathname !== location.pathname || !location.search) {
              return false
            }
            const query = qs.parse(search.substring(1))
            const currentQuery = qs.parse(location.search.substring(1))
            return Object.keys(query).every(
              (key) => query[key] === currentQuery[key],
            )
          } else if (pathname === location.pathname) {
            return true
          }
          return false
        },
        fetcher: ({ url, method, data, config, headers }) => {
          config = config || {}
          config.headers = config.headers || {}
          // config.withCredentials = true

          if (config.cancelExecutor) {
            config.cancelToken = new axios.CancelToken(config.cancelExecutor)
          }

          config.headers = headers || {}
          config.method = method

          if (method === 'get' && data) {
            config.params = data
          } else if (data && data instanceof FormData) {
            // config.headers = config.headers || {};
            // config.headers['Content-Type'] = 'multipart/form-data';
          } else if (
            data &&
            typeof data !== 'string' &&
            !(data instanceof Blob) &&
            !(data instanceof ArrayBuffer)
          ) {
            data = JSON.stringify(data)
            // config.headers = config.headers || {};
            config.headers['Content-Type'] = 'application/json'
          }

          data && (config.data = data)

          return axios(url, config)
        },
        isCancel: (e) => axios.isCancel(e),
        alert,
        notify: (type, msg) => {
          toast[type]
            ? toast[type](msg, type === 'error' ? '系统错误' : '系统消息')
            : console.warn('[Notify]', type, msg)
          console.log('[notify]', type, msg)
        },
        confirm,
        // copy: (contents, options = {}) => {
        //   const ret = copy(contents, options)
        //   ret &&
        //     (!options || options.shutup !== true) &&
        //     toast.info('内容已拷贝到剪切板')
        //   return ret
        // },
      }
    },

    updateRoute(location, replace) {
      if (location === 'goBack') {
        return this.$router.go(-1)
      }
      this.$router[replace ? 'replace' : 'push'](this.normalizeLink(location))
    },

    handleAction(e, action) {
      this.env.alert(`没有识别的动作：${JSON.stringify(action)}`)
    },

    normalizeLink(to) {
      if (/^\/api\//.test(to)) {
        return to
      }
      to = to || ''
      const location = window.location
      if (to && to[0] === '#') {
        to = location.pathname + location.search + to
      } else if (to && to[0] === '?') {
        to = location.pathname + to
      }
      const idx = to.indexOf('?')
      const idx2 = to.indexOf('#')
      let pathname = ~idx
        ? to.substring(0, idx)
        : ~idx2
        ? to.substring(0, idx2)
        : to
      const search = ~idx ? to.substring(idx, ~idx2 ? idx2 : undefined) : ''
      const hash = ~idx2 ? to.substring(idx2) : ''
      if (!pathname) {
        pathname = location.pathname
      } else if (pathname[0] != '/' && !/^https?:\/\//.test(pathname)) {
        const relativeBase = location.pathname
        const paths = relativeBase.split('/')
        paths.pop()
        let m
        while ((m = /^\.\.?\//.exec(pathname))) {
          if (m[0] === '../') {
            paths.pop()
          }
          pathname = pathname.substring(m[0].length)
        }
        pathname = paths.concat(pathname).join('/')
      }
      return pathname + search + hash
    },
  },
}
</script>
