// apps/ant-admin/src/views/amis/vuera.vue
<template>
  <h3>
    This example shows the basic usage of `applyReactInVue`.
  </h3>
  <h4>
    Using React components in Vue components.
  </h4>
  <Basic :foo="foo">
    <div class="slot">
      This is the Vue default slot
      <div>
        current time: {{currentTime}}
      </div>
    </div>
  </Basic>
</template>

<script>
import { onMounted,defineComponent, onUnmounted, ref } from 'vue'
import { applyReactInVue } from 'veaury'
// This is a React Component
import Basic1 from "./react_app/Basic"
export default defineComponent({
  name: 'vuera',
  components: {
    Basic: applyReactInVue(Basic1),
     },
  setup() {
    let timer, timer1
    const currentTime = ref(new Date().toLocaleString())
    const foo = ref(Math.random())
    const showFlag = ref(true)
    onMounted(() => {
      timer = setInterval(() => {
        currentTime.value = new Date().toLocaleString()
        foo.value = Math.random()
      }, 1000)
      timer1 = setTimeout(() => {
        showFlag.value = false
      }, 5000)
    })
    onUnmounted(() => {
      clearInterval(timer)
      clearInterval(timer1)
    })
    return {
      currentTime,
      foo,
      showFlag
    }
  }
})
</script>

<style scoped>
.slot {
  background: aquamarine;
  padding: 10px;
  margin: 10px;
}
</style>

// apps/ant-admin/src/components/Amis/src/Vuera.tsx
// import { applyVueInReact } from 'veaury'
// import BasicVue from './vue/Basic.vue'
// import AAVue from './vue/AA.vue'
import { useEffect, useState, useRef } from 'react'

// const Basic = applyVueInReact(BasicVue)
// const AA = applyVueInReact(AAVue)
export default function () {
    const [state, setState] = useState({
        foo: Math.random(),
        currentTime: new Date().toLocaleString()
    })
    const [aa, setAa] = useState(true)
    const timer = useRef(null)
    const timer1 = useRef(null)
    // useEffect(() => {
    //     timer.current = setInterval(() => {
    //         setState({
    //             foo: Math.random(),
    //             currentTime: new Date().toLocaleString()
    //         })
    //     }, 1000)
    //     timer1.current = setTimeout(() => {
    //         setAa(false)
    //     }, 5000)
    //     return () => {
    //         clearInterval(timer.current)
    //         clearInterval(timer1.current)
    //     }
    // }, [])

    // <Basic foo={state.foo}>
    //         {/* {aa && <AA disappearTime={5}/>} */}
    //         <div className="slot">
    //             This is the Vue component Slot from React<br/>
    //             current time: {state.currentTime}
    //         </div>
    //     </Basic>

    return <div>
        <h3>This example shows the basic usage of `applyVueInReact`.</h3>
        <h4>Using React components in Vue components.</h4>
        
    </div>
}
